import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const ToBSTDemoPage = () => {
    router.push("/tree/bst-demo");
  };
  return (
    <>
      <Head>
        <title>DataStructure - Tree Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="py-2">
        <>
          <h1 className="text-xl md:text-5xl text-center font-bold py-10 border-b">
            DataStructure - Tree Demo
          </h1>
          <div className="container mx-auto py-3">
            <ul className="list-disc">
              <li>
                <div>
                  <h3>Binary Tree - Demo</h3>
                  <p>
                    A binary search tree is a data structure in which each node
                    has at most two children, and the value of each node is
                    greater than or equal to the values of all nodes in its left
                    subtree and less than or equal to the values of all nodes in
                    its right subtree.
                  </p>
                  <button
                    className="bg-yellow-500 border-yellow-500 text-yellow-50 px-4 py-2 border rounded-md hover:bg-yellow-200 hover:border-yellow-200 hover:text-gray-800 focus:outline-none"
                    onClick={ToBSTDemoPage}
                  >
                    Try BST Demo
                  </button>
                </div>
              </li>
              <br></br>
              <li></li>
            </ul>
          </div>
        </>
      </main>
    </>
  );
}
